### ISSUE TITLE
Crear endpoints POST, GET, y PUT para opciones

### ISSUE THREAD

**Issue by jaschulz** [7547-G2/hoy-como-backend#102]
La clase opción tiene los siguientes atributos actualmente en el frontend de BOComercio:
export class Opcion {
  id: number;
  nombre: string;
  precio: number;
  state: string;
}

El PUT, estaría bueno hacerlo como el de los platos, es decir que si te paso algunos datos de la opción, solo modifiques esos. Por ejemplo, si te paso state, solo modificas ese valor, el resto queda igual.

**Comment by fcancel** [comment]
@PostMapping(value = "/backofficeComercio/comercio/{comercioId}/opcion")
@PutMapping(value = "/backofficeComercio/comercio/opcion/{opcionId}")
@GetMapping(value = "/backofficeComercio/opcion/{opcionId}")
@GetMapping(value = "/backofficeComercio/opcion")

**Comment by fcancel** [comment]
Done in #114
