### ISSUE TITLE
Crear endpoint Get y Put para los pedidos

### ISSUE THREAD

**Issue by jaschulz** [7547-G2/hoy-como-backend#103]
El put de un pedido, solo modifica el estado, NADA MÁS.

A partir de el id de un pedido, también necesito un GET para los platos de ese pedido.

Necesito esto por ahora, aunque puede cambiar
Pedidos
export class Pedido {
  id: number;
  monto: number;
  fecha: string;//esto todavia tengo que ver como manejarlo, sobretodo porque ordeno por esto
  estado: string;
}

export class Plato {
  nombre: string;
  opciones: string;//Por ahora devolve null o vacio, porque desde mobile no van
  cantidad: number;
  observacion: string;
}

**Comment by fcancel** [comment]
Hecho en #110
