### ISSUE TITLE
Arreglar el put de comercios

### ISSUE THREAD

**Issue by hiuxmaycry** [7547-G2/hoy-como-backend#131]
Si le envio todos los datos del comercio y trato de actualizarlo, rompe, en este momento existe un solo comercio.
![screenshot at 2018-05-25 16-56-39](https://user-images.githubusercontent.com/11414027/40563828-a2bee280-603c-11e8-940c-985abc165552.png)

**Comment by fcancel** [comment]
@hiuxmaycry Confirmar si está hecho
