### ISSUE TITLE
Modificar GET, POST, y PUT para las opciones en los platos

### ISSUE THREAD

**Issue by jaschulz** [7547-G2/hoy-como-backend#134]
Los platos ahora tienen que venir con un array con todas las opciones en el get (solo el id), y tiene que soportar que se las mande de la misma forma.

**Comment by fcancel** [comment]
En el GET de: /backofficeComercio/{comercioId}/platos
Ahora devuelvo un campo más que es:
¨opcionalIds¨: []

En el PUT de /backofficeComercio/{comercioId}/platos/{platoId}
Ahora espero un nuevo campo de:
¨opcionalIds¨: []
Que en caso de no estar nulo, sobrescribo el valor que tiene el plato

**Comment by fcancel** [comment]
@jaschulz Confirmar si está hecho
