### ISSUE TITLE
Descuentos Backend

### ISSUE THREAD

**Issue by fcancel** [7547-G2/hoy-como-backend#141]

**Comment by fcancel** [comment]
Agrego field descuento e imagenComercio al PUT de /comercios/{comercioId}

Se envía un "descuentoGlobal" en el endpoint /mobileUser/menu/{comercioId}

Confirmar si está hecho
@hiuxmaycry @carlosfurnari @jaschulz

**Comment by carlosfurnari** [comment]
"descuentoGlobal": null, que venga 0 por defecto porfa @fcancel

**Comment by carlosfurnari** [comment]
agregar tambien el campo en el endpoint https://hoy-como-backend.herokuapp.com/api/mobileUser/comercios

**Comment by jaschulz** [comment]
EN el POST funciona ok. En este get no lo trae: 
GET /api/backofficeComercio/{comercioId}

Este último endpoint que traiga tambien imagenComercio, por favor

**Comment by fcancel** [comment]
@carlosfurnari Agregado

**Comment by fcancel** [comment]
@jaschulz agregado

**Comment by carlosfurnari** [comment]
@fcancel @jaschulz ok por mi, se puede cerrar

**Comment by jaschulz** [comment]
Cierro
