### ISSUE TITLE
Get Usuarios

### ISSUE THREAD

**Issue by hiuxmaycry** [7547-G2/hoy-como-backend#147]
Crear un GET de usuarios para backend (React) que traiga todos los usuarios logueados con facebook , con 2 filtros de busqueda. un filtro es nombre y estado donde los estados posibles pueden ser habilitados o deshabilitado

**Comment by hiuxmaycry** [comment]
Crear un PUT de usuarios para backend (react) que modifique el estado de un usuario

**Comment by fcancel** [comment]
Para el GET de usuarios:

Va a ser del tipo /comercios/mobileUsers?search=facebookId:0, state:0

Donde state 0 es activado, 1 desactivado

Para el PUT "/comercios/mobileUser/{mobileUserId}/state" y lo cambia al estado opuesto

@hiuxmaycry Confirmar si está hecho

**Comment by fcancel** [comment]
Sería finalmente:  /comercios/mobileUser?search=firstName:string,lastName:string, state:0
