### ISSUE TITLE
Modificar /api/mobileUser/pedido

### ISSUE THREAD

**Issue by carlosfurnari** [7547-G2/hoy-como-backend#151]
agregar el campo

"extras" : [1,2,3,4,...] dentro del array "orden"

"orden": [
    {
      "cantidad": 0,
      "id_plato": 0,
      "obs": "string",
      "sub_total": 0,
      "extras" : [1,2,3,4,...]
    }
  ],

En el array extras se encuentras los extras solicitados en el plato

**Comment by carlosfurnari** [comment]
agregar tambien los campos:
"lat": "string",
"long": "string"

**Comment by fcancel** [comment]
@carlosfurnari agregado
