### ISSUE TITLE
Agregar nuevo estado al pedido.

### ISSUE THREAD

**Issue by carlosfurnari** [7547-G2/hoy-como-backend#169]
Es necesario tener un nuevo estado "Calificado" para los pedidos, este será seteado por la app mobile,

**Comment by fcancel** [comment]
@carlosfurnari El estado calificado es un campo booleano, string, numérico?

**Comment by carlosfurnari** [comment]
No, seria el ultimo estado posible del flujo, luego de entregado. Es el único que te voy a setear yo desde mobile.

**Comment by carlosfurnari** [comment]
Mejor lo hacemos asi, en vez de setearte yo el estado, lo cambias vos cuando recibis la calificación.
Necesito entonces un endpoint POST, en el path te mando el FacebookId y el id del pedido.
El body va a ser:
{"calificacion": int, "comentario": string}

**Comment by carlosfurnari** [comment]
working
