### ISSUE TITLE
Endpoint para dashboard

### ISSUE THREAD

**Issue by hiuxmaycry** [7547-G2/hoy-como-backend#171]
Crear un edpoint que traiga todos los pedidos de todos los comercios, junto con toda la data de estado del pedido. crear el endpointbajo la ruta de GET "/api/pedidos"

**Comment by fcancel** [comment]
Similar al de: /backofficeComercio/{comercioId}/pedidos   pero para todos los pedidos, no solo para uno en particular.

Con fecha con el siguiente formato: YYYY/mm/dd HH:MM:ss
