### ISSUE TITLE
Modificación endpoint /api/mobileUser/menu/{comercioId}

### ISSUE THREAD

**Issue by carlosfurnari** [7547-G2/hoy-como-backend#172]
Agregar un campo que contenga un vector con los comentarios y replicas.

"comentarios":[{"coment": string, "replica": string}, {"coment": string}]

Puede haber replica o no, si queres mandamelo con null o directamente no lo pongas en el json, lo que te sea mas facil.

**Comment by carlosfurnari** [comment]
@fcancel Te agrego las calificaciones, seria asi:

"comentarios":[{"rating": int, "coment": string, "replica": string}, {"rating": int, "coment": string}]

**Comment by carlosfurnari** [comment]
@fcancel  te lo sigo cambiando jaja, necesito la fecha, en el formato feo q me pasas siempre:

"comentarios":[{"date": string, "rating": int, "coment": string, "replica": string}, {"date": string, "rating": int, "coment": string}]

**Comment by carlosfurnari** [comment]
@fcancel la ultima modificacion, me falta la fecha de la replica:

"comentarios":[{"date": string, "rating": int, "coment": string, "date-rep": string, "replica": string},]

**Comment by carlosfurnari** [comment]
a pedido de ale, añadimos el nombre del usuario:

comentarios":[{"date": string, "rating": int, "user": string, "coment": string, "date-rep": string, "replica": string},]

**Comment by fcancel** [comment]
Sería porque no me deja poner guiones medios, y para diferenciar las dates:
comentarios":
[
{"dateComment": string,
  "rating": int, 
  "user": string,
  "comment": string, 
  "dateReplica": string,
  "replica": string}
]

**Comment by carlosfurnari** [comment]
el formato de la fecha que sea numérico como en el resto de los endpoints de mobile, por favor.

**Comment by fcancel** [comment]
@carlosfurnari Agregado

**Comment by carlosfurnari** [comment]
hecho
