### ISSUE TITLE
Agregar teléfono

### ISSUE THREAD

**Issue by jaschulz** [7547-G2/hoy-como-backend#175]
Agregar el teléfono del usuario a:
GET /api/backofficeComercio/{comercioId}/pedidos

Ejemplo de respuesta:
```json
[
  {
    "id": 26,
    "monto": 2200,
    "fecha": "28/05/2018 02:27",
    "estado": "Despachado",
    "address": "Florida 299,4,C",
    "telefono": "15-5555-5555"
  },
  {
    "id": 56,
    "monto": 270,
    "fecha": "02/06/2018 23:27",
    "estado": "Ingresado",
    "address": "Peru 100,9,B",
    "telefono": "15-5555-5555"
  }
]
```

**Comment by fcancel** [comment]
@jaschulz Agregado
@carlosfurnari  Agregué un campo más cuando se crea un usuario que pide un campo telefono en el json

**Comment by jaschulz** [comment]
Cierro porque me trae el teléfono

**Comment by jaschulz** [comment]
Cargue teléfonos a los users, pero de todos modos el get de los pedidos lo trae NULL. Reabro.

**Comment by jaschulz** [comment]
Ahora si cierro
