### ISSUE TITLE
Change mobileUser/Authorized 

### ISSUE THREAD

**Issue by fcancel** [7547-G2/hoy-como-backend#24]
No existe el user: 
HEADER: 200
{
  "state": 9
}

User habilitado: 
HEADER: 200
{
  "state": 0
  "description": "valor"
}

User Deshabilitado: 
HEADER: 200
{
  "state": 1
  "description": "valor"
}

Si hay algun error interno: 
HEADER: 500

**Comment by carlosfurnari** [comment]
{
  "timestamp": "2018-04-22T03:14:39.955+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "No converter found for return value of type: class ar.uba.fi.hoycomobackend.api.dto.MobileUserStateDto",
  "path": "/api/mobileUser/10155637837533924/authorized"
}
