### ISSUE TITLE
Send mail to Comercio's email when created

### ISSUE THREAD

**Issue by fcancel** [7547-G2/hoy-como-backend#31]
Content of the mail

**Comment by fcancel** [comment]
Acá tenés un link. Varias veces he usado esta página: https://www.mkyong.com/spring/spring-sending-e-mail-via-gmail-smtp-server-with-mailsender/

**Comment by fcancel** [comment]
@jaschulz Javi, después decime que contenido querés que tenga el mail

**Comment by fcancel** [comment]
Cierro, pero vamos a tener que abrir una nueva con el contenido del mail

**Comment by jaschulz** [comment]
Recien veo tu pregunta. Por ahora ponele solo la url: http://localhost:4200/firstlogin?email=mail@mail.com&hash=defaultpasseordhasheada. Por ahora localhost hasta que lo subamos a heroku al BOComercio, y el mail mandamelo siempre a mi cuenta por ahora: javschulz@gmail.com, aunque el mail del querystring tiene que ser el que carga Nico desde BOHoyComo (o nosotros haciendo un POST a la API).
