### ISSUE TITLE
Devolver el nombre del comercio en el POST /api/backofficeComercio/session

### ISSUE THREAD

**Issue by jaschulz** [7547-G2/hoy-como-backend#51]
Es para mostrar el nombre una vez que me logueo.

**Comment by fcancel** [comment]
Se devuelve 
{
    "comercioId": 123
    "token": "ABcd12"
    "name": "name"
}

**Comment by fcancel** [comment]
@jaschulz Chequear para cerrar

**Comment by jaschulz** [comment]
Funciona ok. Lo cierro.
