### ISSUE TITLE
Add platoCategory, and order within the category to api/backofficeComercio/{comercioId}/platos/{platoId}

### ISSUE THREAD

**Issue by jaschulz** [7547-G2/hoy-como-backend#53]
La categoria del plato es mejor que vaya el id, y no la descripcion

{
  "id": 0,
  "imagen": "string",
  "nombre": "string",
  "platoState": "ACTIVO",
  "precio": 0,
  "platoCategory": 0,
  "orden": 0,
}

**Comment by fcancel** [comment]
Ver si no está hecho

**Comment by fcancel** [comment]
@jaschulz confirmar si no está hecho
