### ISSUE TITLE
Modificar GET https://hoy-como-backend.herokuapp.com/api/backofficeComercio/27/platos

### ISSUE THREAD

**Issue by jaschulz** [7547-G2/hoy-como-backend#88]
Agregar al json de rta la descripción de la categoría, SIN SACAR EL ID DE LA CATEGORIA, PORQUE ACTUALMENTE SE USA PARA EL ORDEN DE LOS PLATOS. Eventualmente se le agregara el orden de la categoria, reemplazando al id en lo que al orden respecta.

**Comment by fcancel** [comment]
Done in #100
