### ISSUE TITLE
[Mobile] Crear POST pedidos mobile 

### ISSUE THREAD

**Issue by carlosfurnari** [7547-G2/hoy-como-backend#91]
el body sera:

{
	"facebook_id": 9999,
	"store_id": 8888;
	"order":[
				{
					"id_plato": 77,
					"cantidad": 66,
					"sub_total": 55,
                                        "obs": "string"
				},
				{
					"id_plato": 44,
					"cantidad": 33,
					"sub_total": 22,
                                        "obs": "string"
				}
			],
	"total": 777,
        "address": "string",
        "floor": "string",
        "dep": "string",
        "medioPago": "string",
        "nombreTC": "string",
        "numeroTC": "string",
        "fechaTC": "mm/aa",
        "codigoTC": "string",
}

Los datos de la tarjeta solo seran informados si medioPago es TC, si es efectivo, no
Devolver 200 si esta ok, sin body.

**Comment by fcancel** [comment]
Done in #106

**Comment by fcancel** [comment]
URL: api/mobileUser/pedido
