### ISSUE TITLE
[Mobile] Creat GET de plato

### ISSUE THREAD

**Issue by carlosfurnari** [7547-G2/hoy-como-backend#93]
en el path se incluye id_comercio, id_plato
debe devolver:
{
	"id_plato": 9999,
	"nombre": "string",
	"imagen": "base64",
	"precio": 888,
	"opcionales": [{}]
}

**Comment by fcancel** [comment]
Done in #112

**Comment by fcancel** [comment]
endpoint /api/mobileUser/plato/{platoId}
