### ISSUE TITLE
agregar el comercioId categorias de platos

### ISSUE THREAD

**Issue by hiuxmaycry** [7547-G2/hoy-como-backend#97]
agregar a la categoria de platos , el comercio id para poder filtrarlos por comercio

**Comment by fcancel** [comment]
Se devuelve algo del tipo: [{"id":1,"tipo":"tipoComidaComercio","comercioId":[2]}]

Done in #109

**Comment by fcancel** [comment]
Con respecto a los menues

**Comment by fcancel** [comment]
Hecho junto con #110
